Add pip to setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 export NEED_TO_INSTALL_PYTHON3=false
+export NEED_TO_INSTALL_PYTHON3_PIP=false
 export NEED_TO_INSTALL_DOCKER=false
 export NEED_TO_UPGRADE_PYTHON_TO_38=false
 
@@ -25,6 +26,21 @@ function check_python3_version {
         echo "[WARNING] Will install python3.8 as current version is not expected."
         NEED_TO_UPGRADE_PYTHON_TO_38=true
     fi
+}
+
+function is_python3_pip_installed {
+    PIP_PATH=$(which pip3)
+    if [[ $? -eq 0 ]]; then
+        echo "[INFO] python3-pip is installed. Avilable at ${PIP_PATH}"
+    else
+        NEED_TO_INSTALL_PYTHON3_PIP=true
+    fi
+}
+
+function install_python3_pip {
+    echo "[INFO] Attempting to install python3-pip. If required, please provide password for sudo"
+    sudo apt install -y python3-pip
+    is_python3_pip_installed
 }
 
 function install_python38 {
@@ -57,10 +73,14 @@ function install_docker {
 
 is_python_instaled
 check_python3_version
-if [[ ! ${NEED_TO_INSTALL_DOCKER} ]]; then
+if [[ ${NEED_TO_INSTALL_DOCKER} ]]; then
     install_docker
 fi
 
-if [[ ! ${NEED_TO_INSTALL_PYTHON3} ]]; then
+if [[ ${NEED_TO_INSTALL_PYTHON3} ]]; then
+    install_python38
+fi
+
+if [[ ${NEED_TO_INSTALL_PYTHON3_PIP} ]]; then
     install_python38
 fi
